{% set name = "pyapetnet" %}
{% set version = "1.5.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/gschramm/pyapetnet/archive/refs/tags/v{{ version }}.tar.gz
  sha256: d7eb43e8bd26a8ab3dad1dafae7e19e7ec8a15599b885b2b065c9511d7db818b

build:
  entry_points:
    - pyapetnet_list_models = pyapetnet.scripts.list_models:list_models
    - pyapetnet_predict_from_dicom = pyapetnet.scripts.predict_from_dicom:predict_from_dicom
    - pyapetnet_predict_from_nifti = pyapetnet.scripts.predict_from_nifti:predict_from_nifti
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pdm-backend
    - pip
  run:
    - python >={{ python_min }},<3.11
    - simpleitk >=2.0,<3.dev0
    - pymirc >=0.29,<1.dev0
    - click >=8.0,<9.dev0
    - tensorflow >=2.13,<3.dev0
    - keras >=2.0,<3.dev0

test:
  imports:
    - pyapetnet
  source_files:
    - ./demo_data
    - ./tests
  commands:
    - pip check
    - pyapetnet_list_models
    - pyapetnet_predict_from_dicom --help
    - pyapetnet_predict_from_nifti --help
    - pyapetnet_predict_from_nifti demo_data/brainweb_06_osem_cropped.nii demo_data/brainweb_06_t1_cropped.nii S2_osem_b10_fdg_pe2i --no-save_preproc --verbose --no-coreg_inputs
    - pytest -v tests
  requires:
    - pip
    - pytest
    - python {{ python_min }}

about:
  home: https://github.com/gschramm/pyapetnet
  summary: CNN for anatomy-guided PET reconstruction
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - gschramm
