{% set name = "pyapetnet" %}
{% set version = "1.5.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/gschramm/pyapetnet/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 3a4b27511157b537a3ffe6fd5568ba8b8dfccd15f76c7d989d8ae8453533a256

build:
  number: 1
  noarch: python
  entry_points:
    - pyapetnet_predict_from_nifti=pyapetnet.predict_from_nifti:main
    - pyapetnet_predict_from_dicom=pyapetnet.predict_from_dicom:main
    - pyapetnet_list_models=pyapetnet.list_models:main
  script_env:
    - SETUPTOOLS_SCM_PRETEND_VERSION={{version}}
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools-scm
    - setuptools_scm_git_archive
  run:
    - python >=3.8
    - SimpleITK >=2.0
    - pymirc >=0.29
    - tensorflow >=2.2

test:
  imports:
    - pyapetnet
  source_files:
    - ./demo_data
  commands:
    - pip check
    - pyapetnet_list_models
    - pyapetnet_predict_from_nifti demo_data/brainweb_06_osem_cropped.nii demo_data/brainweb_06_t1_cropped.nii S2_osem_b10_fdg_pe2i --no_preproc_save --verbose --no_coreg
  requires:
    - pip

about:
  home: https://github.com/gschramm/pyapetnet
  summary: a CNN for anatomy-guided deconvolution and denoising of PET images
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - gschramm
