{% set name = "pyapetnet" %}
{% set version = "1.5.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/gschramm/pyapetnet/archive/refs/tags/v{{ version }}.tar.gz
  sha256: f54c13933cb8b0e6f337db3f704de8227e18b3e141b45c7be12ba5fa56b2d52a

build:
  entry_points:
    - pyapetnet_list_models = pyapetnet.scripts.list_models:list_models
    - pyapetnet_predict_from_dicom = pyapetnet.scripts.predict_from_dicom:predict_from_dicom
    - pyapetnet_predict_from_nifti = pyapetnet.scripts.predict_from_nifti:predict_from_nifti
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0
    - wheel
    - setuptools-scm
    - pip
  run:
    - python >={{ python_min }}
    - scipy >1.9 # needed due to bug in solver / incorrect deps of other packages
    - simpleitk ~=2.0
    - pymirc ~=0.29
    - click ~=8.0
    - tensorflow <=2.15

test:
  imports:
    - pyapetnet
  source_files:
    - ./demo_data
    - ./tests
  commands:
    - pip check
    - pyapetnet_list_models
    - pyapetnet_predict_from_dicom --help
    - pyapetnet_predict_from_nifti --help
    - pyapetnet_predict_from_nifti demo_data/brainweb_06_osem_cropped.nii demo_data/brainweb_06_t1_cropped.nii S2_osem_b10_fdg_pe2i --no-save_preproc --verbose --no-coreg_inputs
    - pytest -v tests
  requires:
    - pip
    - pytest
    - python {{ python_min }}

about:
  home: https://github.com/gschramm/pyapetnet
  summary: CNN for anatomy-guided PET reconstruction
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - gschramm
